name: "Generate project archive for AWS Lambda"

on:
  push:
    tags:
      - 'v*'

jobs:
  gen-artifact:
    name: "Generate project archive"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-go@v3"
        with:
          go-version: "^1.20.1"
      - name: "vendor"
        run: |-
          go mod vendor
      - name: "build"
        run: |-
          GOOS=linux GOARCH=amd64 go build -o OnObjectCreated .
      - name: "zip"
        run: zip -r ec2-pivot-dns-lambda.zip .
      - name: Release
        uses: "softprops/action-gh-release@v1"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ec2-pivot-dns-lambda.zip
